name: Deploy Worker
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
#    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Prepare vars
        run: echo "FLOTIQ_API_URL=${{ vars.FLOTIQ_API_URL }}\nFLOTIQ_API_KEY=${{ vars.FLOTIQ_API_KEY }}" >>.env.local 
      - name: Build
        run: yarn run pages:deploy
#      - name: Build & Deploy Worker
#        uses: cloudflare/wrangler-action@v3
#        with:
#          apiToken: ${{ secrets.CF_API_TOKEN }}
#          accountId: ${{ secrets.CF_ACCOUNT_ID }}
#          command: pages deploy --project-name=flotiq-starter-on-pages .vercel/output/static
